import type { FactionDefinition, FactionId, UnitKind, UnitStats } from './types';

export const FACTIONS: Record<FactionId, FactionDefinition> = {
  azure: {
    id: 'azure',
    name: '청람 연방',
    color: 0x006cff,
    accent: '#1688ff',
    doctrine: 'mobility',
  },
  crimson: {
    id: 'crimson',
    name: '적월 공화국',
    color: 0xff1828,
    accent: '#ff3b49',
    doctrine: 'firepower',
  },
  amber: {
    id: 'amber',
    name: '황토 방위령',
    color: 0xffcf00,
    accent: '#ffe13b',
    doctrine: 'entrenchment',
  },
};

export const UNIT_STATS: Record<UnitKind, UnitStats> = {
  infantry: {
    maxHealth: 60,
    speed: 8,
    turnRate: 4.8,
    range: 34,
    reload: 0.55,
    damage: 9,
    projectileSpeed: 95,
    armor: 4,
    cost: 60,
    capturePower: 1,
  },
  tank: {
    maxHealth: 280,
    speed: 12,
    turnRate: 1.25,
    range: 115,
    reload: 3.2,
    damage: 145,
    projectileSpeed: 88,
    armor: 75,
    cost: 260,
    capturePower: 2,
  },
  fighter: {
    maxHealth: 145,
    speed: 65,
    turnRate: 0.95,
    range: 165,
    reload: 0.16,
    damage: 13,
    projectileSpeed: 150,
    armor: 18,
    cost: 420,
    capturePower: 0,
  },
  helicopter: {
    maxHealth: 180,
    speed: 34,
    turnRate: 1.5,
    range: 130,
    reload: 0.22,
    damage: 16,
    projectileSpeed: 130,
    armor: 24,
    cost: 360,
    capturePower: 0,
  },
  drone: {
    maxHealth: 48,
    speed: 27,
    turnRate: 2.8,
    range: 72,
    reload: 1.4,
    damage: 34,
    projectileSpeed: 78,
    armor: 3,
    cost: 120,
    capturePower: 0,
  },
};

export const WORLD = {
  chunkSize: 96,
  chunkRadius: 3,
  gravity: 18,
  waterLevel: -1.7,
  battlefieldRadius: 430,
  outpostCaptureRadius: 19,
  outpostCaptureTime: 7,
  resourceTick: 2,
  diplomacyInterval: 45,
  maxProjectiles: 180,
  maxRubble: 220,
} as const;
